export const line1 = [
  "/images/skills/skill (1).png",
  "/images/skills/skill (2).png",
  "/images/skills/skill (3).png",
  "/images/skills/skill (4).png",
  "/images/skills/skill (5).png",
  "/images/skills/skill (6).png",
  "/images/skills/skill (7).png",
  "/images/skills/skill (8).png",
  "/images/skills/skill (9).png",
  "/images/skills/skill (10).png",
  "/images/skills/skill (11).png",
  "/images/skills/skill (12).png",
  "/images/skills/skill (13).png",
  "/images/skills/skill (14).png",
  "/images/skills/skill (15).png",
  "/images/skills/skill (15).png",
  "/images/skills/skill (15).png",
];
export const line2 = [
  "/images/skills/skill (5).png",
  "/images/skills/skill (6).png",
  "/images/skills/skill (7).png",
  "/images/skills/skill (8).png",
  "/images/skills/skill (9).png",
  "/images/skills/skill (10).png",
  "/images/skills/skill (11).png",
  "/images/skills/skill (12).png",
  "/images/skills/skill (13).png",
  "/images/skills/skill (14).png",
  "/images/skills/skill (15).png",
  "/images/skills/skill (1).png",
  "/images/skills/skill (2).png",
  "/images/skills/skill (3).png",
  "/images/skills/skill (4).png",
];
export const line3 = [
  "/images/skills/skill (10).png",
  "/images/skills/skill (11).png",
  "/images/skills/skill (12).png",
  "/images/skills/skill (13).png",
  "/images/skills/skill (14).png",
  "/images/skills/skill (15).png",
  "/images/skills/skill (1).png",
  "/images/skills/skill (2).png",
  "/images/skills/skill (3).png",
  "/images/skills/skill (4).png",
  "/images/skills/skill (5).png",
  "/images/skills/skill (6).png",
  "/images/skills/skill (7).png",
  "/images/skills/skill (8).png",
  "/images/skills/skill (9).png",
];
